name: checkout

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout action 
        uses: actions/checkout@v4 
      - name: use the script 
        run: | 
          ls -la
        shell: bash  
      - name: shell scrpit 
        run: ./dummy.sh
        
  
