name: compostite caller   
on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step java and python 
        uses: thamizharasan-nss/installjavapythonaction@main

      - name: Ds java version
        run: java --version 

      - name: py version 
        run: python --version
