name: dummy workflow

on:
  workflow_dispatch: 
    inputs:
      name:
        description: 'Name'
        default: 'test' 
        type: string 
      age:
        type: choice
        description: 'Age'
        default: 
          - Male
          - Female
       required: true   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install git 
      run: |
        sudo apt install git 
        git --version 

    - name: clone 
      run: |
        mkdir app
        ls -la app

    - name: print input
      run: echo "${{ inputs.name }}"

      
  
