name: using the env in  workflow 

on:
  push:

env: 
   app: WEBAPP
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: using the env 
        run: echo "using the app ${{ env.app }}"

  deploy:
     runs-on: ubuntu-latest
     needs: build
     env:
       team: SRE
     steps:
       - name: using the job level 
         run: echo "we are in the team ${{ env.team }}" 

  tests:
     runs-on: ubuntu-latest
     needs: deploy
     steps:
       - name: using the step level 
         env:
           owner: thamizh
         run: echo "The name of owner is ${{ env.owner }}"  

       - name: uisng the repo level scrects
         run: echo ${{ secrets.AWS_REGION }}

  repoenv:
     runs-on: ubuntu-latest
     needs: tests
     steps:
       - name: using the repo level env variable 
         run: echo "dummy value ${{ vars.DOCKERHUB_USERNAME }}"
         
           
          
    
    
