name: upload and download 
on:
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print the date 
        run: date >> sample.txt
        
      - name: cat the sample.txt
        run: cat sample.txt

      - name: upload the file 
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact 
          path: sample.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build   # âœ… REQUIRED
    steps:
      - name: download the artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: my-artifact

      - name: read the file
        run: |
          ls -l my-artifact
          cat my-artifact/sample.txt
          

        
