name: upload and download 
on:
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print the date 
        run: date >> sample.txt
        
      - name: cat the sample.txt
        run: cat sample.txt

      - name: upload the file 
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact 
          path: sample.txt

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: download the artifact 
        uses: actions/download-artifact@v4
        with:
          name: my-artifact 
      - name: unzip 
        run: |
           unzip my-artifact
           cd my-artifact
           cat sample.txt
          

        
